using UnrealBinaryBuilder.Avalonia.Models;
using System;

namespace UnrealBinaryBuilder.Avalonia.Classes.Interfaces;

/// <summary>
/// Provides a service for managing and persisting builder application settings and accessing the application log file.
/// </summary>
public interface ISettingsService
{
    /// <summary>
    /// Retrieves the current builder settings.
    /// </summary>
    /// <returns>The loaded builder settings.</returns>
    BuilderSettingsJson GetSettings();

    /// <summary>
    /// Saves the specified builder settings to persistent storage.
    /// </summary>
    /// <param name="settings">The settings to save.</param>
    void SaveSettings(BuilderSettingsJson settings);

    /// <summary>
    /// Writes the specified content to the application's general log file.
    /// </summary>
    /// <param name="content">The content to write to the log.</param>
    void WriteToLogFile(string content);

    /// <summary>
    /// Writes the specified content to the application's error log file.
    /// </summary>
    /// <param name="content">The error content to write to the log.</param>
    void WriteErrorsToLogFile(string content);

    /// <summary>
    /// Opens the folder containing the application's log files in the default file explorer.
    /// </summary>
    void OpenLogFolder();

    /// <summary>
    /// Opens the application settings configuration file in the default text editor.
    /// </summary>
    void OpenSettings();
    
    /// <summary>
    /// Event triggered when a log message is generated by the settings service or related operations.
    /// </summary>
    event Action<string, LogMessageType>? OnLog;
}
